# Local configuration for The Great Sage trading bot
# Replace the placeholder values with your own API keys
alphavantage:
  api_key: "YOUR_ALPHA_VANTAGE_API_KEY"
newsapi:
  api_key: "YOUR_NEWSAPI_KEY"
